language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/sequel_4.x.gemfile
  - gemfiles/sequel_5.x.gemfile
  - gemfiles/sequel_latest.gemfile
before_install:
  - gem update --system
  - gem update bundler
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
env:
  global:
    DATABASE_URL=postgres:///travis_ci_test
services:
- postgresql
notifications:
  email: false
addons:
  artifacts:
    paths: test/database.log
  postgresql: "9.4"
