language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/sequel_4.x.gemfile
  - gemfiles/sequel_5.x.gemfile
  - gemfiles/sequel_latest.gemfile
before_install:
  - gem update --system
  - gem update bundler
notifications:
  email: false
